-- AlterTable
ALTER TABLE `payment` MODIFY `paymentStatus` ENUM('PENDING', 'PAID', 'EXPIRED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `transaction` MODIFY `status` ENUM('PENDING', 'PAID', 'EXPIRED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    MODIFY `paymentStatus` ENUM('PENDING', 'PAID', 'EXPIRED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING';
